[tool.poetry]
name = "pee-a-no"
version = "0.1.0"
description = "A simple coding project"
authors = ["brian"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
